# Mutations for User operations
mutation UpdateUser(
  $id: String!
  $email: String!
  $username: String!
  $name: String
  $company: String
  $address: String
  $city: String
  $postalCode: String
  $country: String
  $aboutMe: String
  $profileImg: String
  $role: String
  $status: String
  $reminders: Boolean
  $language: String
  $recentActivity: Boolean
  $twoFactor: Boolean
  $postNotifications: Boolean
) @auth(level: PUBLIC) {
  user_upsert(
    data: {
      id: $id
      email: $email
      username: $username
      name: $name
      company: $company
      address: $address
      city: $city
      postalCode: $postalCode
      country: $country
      aboutMe: $aboutMe
      profileImg: $profileImg
      role: $role
      status: $status
      reminders: $reminders
      language: $language
      recentActivity: $recentActivity
      twoFactor: $twoFactor
      postNotifications: $postNotifications
    }
  )
}

mutation DeleteUser($id: String!) @auth(level: PUBLIC) {
  user_update(id: $id, data: { status: "Deleted" })
}

mutation RestoreUser($id: String!) @auth(level: PUBLIC) {
  user_update(id: $id, data: { status: "Active" })
}
