# Queries for User operations

query ListUsers @auth(level: PUBLIC) {
  users(where: { status: { ne: "Deleted" } }) {
    id
    username
    name
    email
    role
    creationDate
    status
  }
}

query GetUserById($id: String!) @auth(level: PUBLIC) {
  user(id: $id) {
    id
    username
    name
    email
    role
    status
    creationDate
    company
    address
    city
    postalCode
    country
    aboutMe
    profileImg
    posts
    followers
    following
    reminders
    language
    recentActivity
    twoFactor
    postNotifications
  }
}

query ListDeletedUsers @auth(level: PUBLIC) {
  users(where: { status: { eq: "Deleted" } }) {
    id
    username
    name
    email
    role
    creationDate
    status
  }
}

