# Example schema for simple movie review app

# User table is keyed by Firebase Auth UID.
type User @table {
  # `@default(expr: "auth.uid")` sets it to Firebase Auth UID during insert and upsert.
  id: String!
  username: String! @col(dataType: "varchar(50)")
  name: String @col(dataType: "varchar(100)")
  email: String! @unique
  role: String @col(dataType: "varchar(50)") @default(value: "Consumer")
  status: String @col(dataType: "varchar(20)") @default(value: "Pending")
  creationDate: Timestamp! @default(expr: "request.time")

  # Profile details
  company: String
  address: String
  city: String
  postalCode: String
  country: String
  aboutMe: String
  profileImg: String

  # Social statistics
  posts: String
  followers: String
  following: String

  # Settings
  reminders: Boolean @default(value: false)
  language: String
  recentActivity: Boolean @default(value: false)
  twoFactor: Boolean @default(value: false)
  postNotifications: Boolean @default(value: false)
}
